// FILE: 01-config.gs
var CONFIG = this.CONFIG || {
  PASTORS_SHEET: 'Pastors',
  DELEGATES_SHEET: 'Delegates',
  HEADER_ROW: 1,
  CONF_START: '2026-03-02',
  CONF_END:   '2026-03-07',
  CONF_NIGHTS: 5
};
var PASTORS_SHEET   = CONFIG.PASTORS_SHEET;
var DELEGATES_SHEET = CONFIG.DELEGATES_SHEET;
var HEADER_ROW      = CONFIG.HEADER_ROW;
